### ISSUE TITLE
Drop elm- from package name

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-community/dict-extra#3]
As per this: https://github.com/elm-community/Manifesto/issues/27.

**Comment by Skinney** [comment]
Hmm. I ready to do this. But do I have the rights to change the repo name?

**Comment by jvoigtlaender** [comment]
I do, and I have just changed the name on GitHub. The `elm-package.json` etc. should be in your reach?

**Comment by Skinney** [comment]
Done. Looks good?

**Comment by jvoigtlaender** [comment]
Yes, looks good. So it seems what remains is to delete the old tag `1.0.0`, create a new one at the current repo content, then publish to the package site.
