### ISSUE TITLE
Package needs a maintainer

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-community/dict-extra#7]
According to https://github.com/elm-community/Manifesto/blob/master/maintainers.md, no maintainer is assigned for this package.

@Skinney, are you willing to take that role?

The role of a maintainer is briefly explained here: https://github.com/elm-community/Manifesto/blob/master/README.md#the-role-of-a-maintainer

**Comment by Skinney** [comment]
I thought I already was the maintainer, so yes :)

**Comment by jvoigtlaender** [comment]
:smile:

Can you make a PR there? I don't know which email address you want to add for yourself.

**Comment by Skinney** [comment]
Done
